//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrushFilter.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrushFilter.Globalization.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a directory to add to the list of places to load custom brushes from..
        /// </summary>
        internal static string AddFolderTip {
            get {
                return ResourceManager.GetString("AddFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Intensity shortcut: Ctrl +I + Mouse Wheel. Sets the intensity of the effect..
        /// </summary>
        internal static string BrushIntensityTip {
            get {
                return ResourceManager.GetString("BrushIntensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Directories To Auto-Load.
        /// </summary>
        internal static string BrushLocations {
            get {
                return ResourceManager.GetString("BrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to look for brushes appear here. Type a new address or use &apos;add folder&apos; to add your own..
        /// </summary>
        internal static string BrushLocationsTextboxTip {
            get {
                return ResourceManager.GetString("BrushLocationsTextboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc. brush options.
        /// </summary>
        internal static string BrushOptions {
            get {
                return ResourceManager.GetString("BrushOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush rotation shortcut: Ctrl + R + Mouse Wheel. Sets the brush rotation for tilting while drawing..
        /// </summary>
        internal static string BrushRotationTip {
            get {
                return ResourceManager.GetString("BrushRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose another brush to use (or import your own)..
        /// </summary>
        internal static string BrushSelectorTip {
            get {
                return ResourceManager.GetString("BrushSelectorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush size shortcut: Ctrl + S + Mouse Wheel. Sets the brush size to make it larger or smaller..
        /// </summary>
        internal static string BrushSizeTip {
            get {
                return ResourceManager.GetString("BrushSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving changes..
        /// </summary>
        internal static string CancelTip {
            get {
                return ResourceManager.GetString("CancelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Zoom:.
        /// </summary>
        internal static string CanvasZoom {
            get {
                return ResourceManager.GetString("CanvasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas zoom shortcut: Ctrl + Mouse Wheel. Zooms the picture in and out to make editing easier..
        /// </summary>
        internal static string CanvasZoomTip {
            get {
                return ResourceManager.GetString("CanvasZoomTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Custom Brushes.
        /// </summary>
        internal static string ClearBrushes {
            get {
                return ResourceManager.GetString("ClearBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any custom brushes that were added. The normal brushes will remain..
        /// </summary>
        internal static string ClearBrushesTip {
            get {
                return ResourceManager.GetString("ClearBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        internal static string ClearSettings {
            get {
                return ResourceManager.GetString("ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all settings to the default values they had when the plugin first loaded..
        /// </summary>
        internal static string ClearSettingsTip {
            get {
                return ResourceManager.GetString("ClearSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Locations.
        /// </summary>
        internal static string CustomBrushLocations {
            get {
                return ResourceManager.GetString("CustomBrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define where to look for brushes when this plugin loads..
        /// </summary>
        internal static string CustomBrushLocationsTip {
            get {
                return ResourceManager.GetString("CustomBrushLocationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle click and drag to pan image. Right-click for options. Hover over items for details..
        /// </summary>
        internal static string GeneralTooltip {
            get {
                return ResourceManager.GetString("GeneralTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Intensity:.
        /// </summary>
        internal static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Brushes?.
        /// </summary>
        internal static string LoadDefaultBrushes {
            get {
                return ResourceManager.GetString("LoadDefaultBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned off, only the circle brush and any custom brushes will be loaded..
        /// </summary>
        internal static string LoadDefaultBrushesTip {
            get {
                return ResourceManager.GetString("LoadDefaultBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Draw Distance:.
        /// </summary>
        internal static string MinDrawDistance {
            get {
                return ResourceManager.GetString("MinDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each brush stroke must be at least this far apart to have an effect..
        /// </summary>
        internal static string MinDrawDistanceTip {
            get {
                return ResourceManager.GetString("MinDrawDistanceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and finish..
        /// </summary>
        internal static string OkTip {
            get {
                return ResourceManager.GetString("OkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate With Mouse.
        /// </summary>
        internal static string OrientToMouse {
            get {
                return ResourceManager.GetString("OrientToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the brush rotates with the mouse. If the brush appears to point to the right, it will look accurate. If it does not, try adjusting rotation to fix it..
        /// </summary>
        internal static string OrientToMouseTip {
            get {
                return ResourceManager.GetString("OrientToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Spray:.
        /// </summary>
        internal static string RandHorzShift {
            get {
                return ResourceManager.GetString("RandHorzShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved left or right this much..
        /// </summary>
        internal static string RandHorzShiftTip {
            get {
                return ResourceManager.GetString("RandHorzShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Intensity:.
        /// </summary>
        internal static string RandMaxIntensity {
            get {
                return ResourceManager.GetString("RandMaxIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the maximum intensity of the effect of the brush will randomly jitter so it will sometimes be normal and sometimes more intense..
        /// </summary>
        internal static string RandMaxIntensityTip {
            get {
                return ResourceManager.GetString("RandMaxIntensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Size:.
        /// </summary>
        internal static string RandMaxSize {
            get {
                return ResourceManager.GetString("RandMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much bigger..
        /// </summary>
        internal static string RandMaxSizeTip {
            get {
                return ResourceManager.GetString("RandMaxSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Intensity:.
        /// </summary>
        internal static string RandMinIntensity {
            get {
                return ResourceManager.GetString("RandMinIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the maximum intensity of the effect of the brush will randomly jitter so it will sometimes be normal and sometimes less intense..
        /// </summary>
        internal static string RandMinIntensityTip {
            get {
                return ResourceManager.GetString("RandMinIntensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Size:.
        /// </summary>
        internal static string RandMinSize {
            get {
                return ResourceManager.GetString("RandMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much smaller..
        /// </summary>
        internal static string RandMinSizeTip {
            get {
                return ResourceManager.GetString("RandMinSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Left:.
        /// </summary>
        internal static string RandRotLeft {
            get {
                return ResourceManager.GetString("RandRotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the left..
        /// </summary>
        internal static string RandRotLeftTip {
            get {
                return ResourceManager.GetString("RandRotLeftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Right:.
        /// </summary>
        internal static string RandRotRight {
            get {
                return ResourceManager.GetString("RandRotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the right..
        /// </summary>
        internal static string RandRotRightTip {
            get {
                return ResourceManager.GetString("RandRotRightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spray:.
        /// </summary>
        internal static string RandVertShift {
            get {
                return ResourceManager.GetString("RandVertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved up or down this much..
        /// </summary>
        internal static string RandVertShiftTip {
            get {
                return ResourceManager.GetString("RandVertShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Shortcut: Ctrl + Y. Restores changes removed by undo, if possible..
        /// </summary>
        internal static string RedoTip {
            get {
                return ResourceManager.GetString("RedoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Rotation:.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all changes in the preferences..
        /// </summary>
        internal static string SavePreferencesTip {
            get {
                return ResourceManager.GetString("SavePreferencesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Shift:.
        /// </summary>
        internal static string ShiftIntensity {
            get {
                return ResourceManager.GetString("ShiftIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the effect&apos;s intensity will change by this much..
        /// </summary>
        internal static string ShiftIntensityTip {
            get {
                return ResourceManager.GetString("ShiftIntensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Shift:.
        /// </summary>
        internal static string ShiftRotation {
            get {
                return ResourceManager.GetString("ShiftRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will tilt by this much..
        /// </summary>
        internal static string ShiftRotationTip {
            get {
                return ResourceManager.GetString("ShiftRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Shift:.
        /// </summary>
        internal static string ShiftSize {
            get {
                return ResourceManager.GetString("ShiftSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush size will change by this much..
        /// </summary>
        internal static string ShiftSizeTip {
            get {
                return ResourceManager.GetString("ShiftSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush can be mirrored horizontally and/or vertically..
        /// </summary>
        internal static string SymmetryTip {
            get {
                return ResourceManager.GetString("SymmetryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string TabColor {
            get {
                return ResourceManager.GetString("TabColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string TabControls {
            get {
                return ResourceManager.GetString("TabControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter.
        /// </summary>
        internal static string TabJitter {
            get {
                return ResourceManager.GetString("TabJitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string TabOther {
            get {
                return ResourceManager.GetString("TabOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Filter.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Shortcut: Ctrl + Z. Undo the last drawing, if possible..
        /// </summary>
        internal static string UndoTip {
            get {
                return ResourceManager.GetString("UndoTip", resourceCulture);
            }
        }
    }
}
